BEGIN;

-- 1
CREATE TABLE funcionario (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(45),
    idade INT
);

-- 2
CREATE TABLE planta (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(45),
    luz_diaria FLOAT,
    agua_diaria FLOAT
);

CREATE TABLE canteiro (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(45),
    luz_diaria FLOAT,
    agua_diaria FLOAT
);

-- 3
CREATE TABLE plantio (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_plantio DATE,
    sementes FLOAT,
    planta_id INT,
    FOREIGN KEY (planta_id) REFERENCES planta (id),
    funcionario_id INT,    
    FOREIGN KEY (funcionario_id) REFERENCES funcionario (id)
    ON DELETE CASCADE,
    canteiro_id INT,
    FOREIGN KEY (canteiro_id) REFERENCES canteiro (id)
    ON DELETE CASCADE
);

-- 4
ALTER TABLE funcionario
DROP COLUMN idade;

-- 5
ALTER TABLE funcionario
ADD COLUMN data_nascimento DATE;

-- 6
INSERT INTO canteiro (id, nome, luz_diaria, agua_diaria)
VALUES (1, 'o da esquina', 120, 240);

-- 8
INSERT INTO funcionario (id, nome, data_nascimento)
VALUES (3, 'nameless joe', '2001-09-11');

INSERT INTO planta (id, nome, luz_diaria, agua_diaria)
VALUES (2, 'feijao', 145, 6436);

-- 7
INSERT INTO plantio (data_plantio, sementes, planta_id, funcionario_id, canteiro_id)
VALUES ('2001-09-11', 666, 2, 3, 1);

-- 9
DELETE FROM funcionario;

-- 10
DELETE FROM planta 
WHERE agua_diaria > 5;

-- 11
UPDATE canteiro
SET luz_diaria = 5;

-- 12
UPDATE canteiro
SET agua_diaria = 10
WHERE agua_diaria < 7;

COMMIT;